feat(btn): support dashed variant
jd-solanki/anu pull request #3
Opened 2022-09-07 14:14 UTC by zguolee

2022-09-07 14:42 UTC, zguolee commented
Sorry, I was affected by the variant attribute and forgot to be able to add it directly through the `class`.🥲 Thank you for this project, very awesome, I also learned a lot.

2022-09-07 14:45 UTC, jd-solanki commented
> Sorry, I was affected by the variant attribute and forgot to be able to add it directly through the `class`.🥲 Thank you for this project, very awesome, I also learned a lot.

Thanks for the PR anyways. I can't express how happy I am that you gave PR ❤️ 

Happy coding 🙌🏻

2022-09-07 17:40 UTC, jd-solanki commented
While driving back home, I thought your PR is actually useful in other terms. We still have to add `!` (_important_) before `border-dashed`.

Moreover, we have `border border-solid` in `useLayer` which generates duplicate styles for `border-style` property.

Thanks to your PR, we can allow `border-dashed` without `!` and remove the duplicate styles.

2022-09-07 18:07 UTC, jd-solanki commented on packages/documentation/docs/guide/components/button.md
> +
```suggestion
:::details Customize `border-style` of outlined buttons
To create outlined button with different border style just add relevant class.

e.g. To create outline button with dashed border, add `border-dashed` class.
:::

```

2022-09-07 18:11 UTC, jd-solanki commented on packages/anu-vue/src/composables/useLayer.ts
>      if (props.color) {
For `props.variant === 'outline'` condition use below:
```diff
-        classes.push(`border border-solid border-${props.color} text-${props.color} typography-title-${props.color} typography-subtitle-${props.color} typography-text-${props.color} typography-subtitle-opacity-100 typography-text-opacity-100`)
+        classes.push(`border-width-1 uno-layer-base-border-solid border-${props.color} text-${props.color} typography-title-${props.color} typography-subtitle-${props.color} typography-text-${props.color} typography-subtitle-opacity-100 typography-text-opacity-100`)
```

2022-09-07 18:13 UTC, jd-solanki requested changes
I want to give you credit for your first PR in this repo ❤️ 

Can you please make mentioned changes so we can merge the PR.

Thanks.

2022-09-08 04:10 UTC, jd-solanki requested changes
Apart from the two changes, everything else is correct.

Thanks for simplifying `useLayer` composable.

2022-09-08 04:10 UTC, jd-solanki commented on packages/anu-vue/src/composables/useLayer.ts
>      if (props.color) {
Yes 💯 

Can you please perform below changes:
```diff
        if (props.variant === 'outline')
          classes.push(`border border-${props.color}`)
        if (props.variant === 'outline')
-          classes.push(`border border-${props.color}`)
+          classes.push(`border-width-1 uno-layer-base-border-solid border-${props.color}`)
```

2022-09-08 04:10 UTC, jd-solanki commented on packages/anu-vue/src/composables/useLayer.ts
> +      validator: (value: string) => ['fill', 'outline', 'dashed', 'light', 'text'].includes(value),
We don't need `dashed` this validator as well

2022-09-08 05:41 UTC, zguolee commented
> Out of curiosity, I wanted to ask, have you enabled "[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?

I checked and it was enabled.

2022-09-08 06:14 UTC, jd-solanki approved these changes

2022-09-08 06:17 UTC, merged